name: Priyanka Saggu
url: 'https://priyankasaggu11929.github.io/blog'
description: 'I speak here {^_^}'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Priyanka Saggu'
disqus_shortname: priyankasaggu119
google_analytics: UA-42209870-1

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
