title: Priyanka Saggu
url: 'https://priyankasaggu11929.github.io'
description: 'I speak here {^_^}'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

paginate: 10
paginate_path: "blog/page:num"

author: 'Priyanka Saggu'
disqus_shortname: priyankasaggu119
google_analytics: UA-42209870-1

plugins:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
