title: Priyanka Saggu
url: 'https://psaggu.com'
description: 'I speak here {^_^}'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

paginate: 10
paginate_path: /page:num/

excerpt_separator: "<!-- break -->"

author: 'Priyanka Saggu'
disqus_shortname: priyankasaggu119
google_analytics: UA-42209870-1

plugins:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-paginate

sass:
    sass_dir: _sass
    style: :compressed
